### ISSUE TITLE
GOG Galaxy 2.0 is not detecting Dolphin Roms

### ISSUE THREAD

**Issue by DoyesBoyes** [JTNDev/galaxy-integration-wii#1]
So I just implemented this plugin, set up my paths (with / and not \) and renamed a few of my ISOs to better reflect the Index.txt, yet GOG Galaxy 2.0 does not detect them.

Here's my `user_config`
![ss+(2019-08-14+at+10 39 46)](https://user-images.githubusercontent.com/53980835/63069335-7833ea80-bee4-11e9-98af-194c0ecc94a5.png)

Here's my ROM folder (note not all of them have been renamed but I did do to a few of them as a test)
![ss+(2019-08-14+at+10 40 44)](https://user-images.githubusercontent.com/53980835/63069367-9d285d80-bee4-11e9-9bde-33ea6e93c7b2.png)

**Comment by JTNDev** [comment]
Hi, a couple of hours ago I deleted the binary for the application and forgot to replace it, so I'm assuming you downloaded the source code. The program relies on the folder integration being named "dolphin_fc3e85e4-c66b-4310-96c0-8f95cc43e546" while in the source code if you download it, it would be "galaxy-integration-wii-0.1.0". Try renaming the integration folder in Galaxy\plugins\Installed or download the binary I just posted and extract it into the integration folder. Let me know if it works!

**Comment by DoyesBoyes** [comment]
Hey I downloaded the latest release (0.1.1) but it doesn't seem to have fixed the problem.

**Comment by JTNDev** [comment]
Can I see your galaxy integration and the plugin's folder? Thanks

**Comment by Curotos** [comment]
I downloaded the updated version as well and it didn't fix it either,
![gog](https://user-images.githubusercontent.com/54136079/63119410-1ae47b80-bf6e-11e9-8a38-8bd91f052923.png)

**Comment by JTNDev** [comment]
@Curotos  The reason why it's not working is the "galaxy-integration-wii-master" folder must be named "dolphin_fc3e85e4-c66b-4310-96c0-8f95cc43e546". It seems like you download the source code not binary which is why the folder is named that way. Try copying the folder from [here](https://github.com/JTNDev/galaxy-integration-wii/releases/download/v0.1.1/galaxy-integration-wii-v0.1.1.zip) or rename the folder to "dolphin_fc3e85e4-c66b-4310-96c0-8f95cc43e546"

**Comment by Curotos** [comment]
I tried renaming the folder and it did not work then I tried downloading the folder you linked and it still isn't working?

**Comment by JTNDev** [comment]
Can you please show me your user config file? Also, is it not showing up in Galaxy or are the games not importing?

**Comment by Curotos** [comment]
It is being detected by galaxy and it creates the tab for Nintendo Wii it just doesn't import the roms
![gog user](https://user-images.githubusercontent.com/54136079/63133879-1bdcd380-bf95-11e9-97ff-65dfdb55576d.png)

**Comment by JTNDev** [comment]
It works for Wii games not GameCube games, do you keep your Wii and GameCube games in the same folder? Also, can I please see your ROMs folder so I can see if the ROM names are right?

**Comment by Curotos** [comment]
Ah I see, yes I keep them both in the same folder for dolphin.
![gog roms](https://user-images.githubusercontent.com/54136079/63134270-b689e200-bf96-11e9-955b-12b1e8d51397.png)

**Comment by JTNDev** [comment]
I've never tested the program with iso files before, just wbfs so I'll see if that's the problem and get it working with ISOs. I might not be able to do it today but I'll try to narrow down the problem as soon as possible

**Comment by Curotos** [comment]
I gotcha, thatd be awesome! No rush, i'm just super excited to get these emulators running in galaxy!

**Comment by Curotos** [comment]
Really weird after leaving it alone for a while I reopened it and it imported some of the roms?
![gog games](https://user-images.githubusercontent.com/54136079/63136099-6282fb80-bf9e-11e9-99eb-28c2d94f7366.png)

**Comment by JTNDev** [comment]
I think I've finally figured out the problem. Can you put Batman, Wind Waker and TMNT in a separate folder, and try disconnecting and reconnecting the plugin?
I think the problem is that games with a ":" in their names aren't recognized by my plugin and I've noticed that if one game isn't recognized, none of the games get imported.
Also, I didn't realize GameCube games are in the index file so GameCube games will work as well!

**Comment by Curotos** [comment]
Alright the only two games that aren't showing now are wind waker and tmnt, plus I was able to edit the unknown games using the gog meta data thingy. They all run perfectly through gog!

**Comment by DoyesBoyes** [comment]
@JTNDev I can confirm that games that have a ":" in there title aren't recognised. I got it to work by putting games that don't have have symbols in them (:, -, etc...) and they were picked up. As soon as I put a game with a - in the title it fails to get recognized. Can I suggest maybe implementing GiantBomb API support since I believe that can circumnavigate the problem (assuming of course you can). I know the PCSX2 plugin did this and that was the only way I was able to get the plugin to read my folder.

**Comment by JTNDev** [comment]
@Curotos I'll try to implement GiantBomb API support eventually, and I'll
also try to enable support for games with symbols in them!

**Comment by Curotos** [comment]
Alright dope thank you my man, you are genuinely giving us an ultimate gaming experience!

**Comment by DoyesBoyes** [comment]
I think it's safe to close this issue out now
