### ISSUE TITLE
zip release option

### ISSUE THREAD

**Issue by Slashbunny** [JTNDev/galaxy-integration-wii#14]
Greetings, 

The latest release only has a 7z version. When using plugin auto-update tools like https://github.com/Slashbunny/gog-galaxy-plugin-downloader , it makes it difficult since there are not any programmatic 7z libraries. You have to basically fork out to a 7z process to do processing and worry about cross-platform concerns and whether or not the user has 7zip installed. 

Any chance you can do releases with just a normal zip file?

Thanks!

**Comment by JTNDev** [comment]
Yes, I'll fix it right now.

**Comment by Slashbunny** [comment]
Thanks, I updated the above tool's manifest to pull in 0.5.0 🎉
