### ISSUE TITLE
No WAD Virtual Console files added

### ISSUE THREAD

**Issue by ahnernoch** [JTNDev/galaxy-integration-wii#15]
I would love to see the intergration also addind parsing WAD files to be opened with dolphin. tHanks for your nice work.

**Comment by JTNDev** [comment]
Thanks for the suggestion! I just added it into v0.5.1.

**Comment by ahnernoch** [comment]
Thanks for the time and work….

 

Von: Joshua <notifications@github.com> 
Gesendet: Freitag, 3. April 2020 17:18
An: JTNDev/galaxy-integration-wii <galaxy-integration-wii@noreply.github.com>
Cc: ahnernoch <guthpascal@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [JTNDev/galaxy-integration-wii] No WAD Virtual Console files added (#15)

 

Thanks for the suggestion! I just added it into v0.5.1.
