### ISSUE TITLE
Wii games "Not Compatible"

### ISSUE THREAD

**Issue by ResKraven** [JTNDev/galaxy-integration-wii#21]
I can't launch my games since GOG Galaxy mark them as "Not Compatible" I have no idea of what to do. I think I've done anything right since every game is detected.
Thanks for your help.
![Immagine 2020-12-09 152707](https://user-images.githubusercontent.com/75739754/101642406-4593f680-3a33-11eb-8c63-571bd58384de.png)
![Immagine 2020-12-09 152751](https://user-images.githubusercontent.com/75739754/101642410-46c52380-3a33-11eb-9006-e663b4573b47.png)
![Immagine 2020-12-09 152852](https://user-images.githubusercontent.com/75739754/101642411-46c52380-3a33-11eb-9167-a0ce8b5a4e06.png)

**Comment by JasSuri** [comment]
This happening on all the integrations 
https://github.com/Mixaill/awesome-gog-galaxy/issues/97
