### ISSUE TITLE
[Request] Find games in subfolders

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [JTNDev/galaxy-integration-wii#8]
Can the limitation of all .wbfs files having to be in the same folder be removed? If I have to both name them after the game id and also all not have them in subfolders I have no easy way to know which file is which.

**Comment by JTNDev** [comment]
Yes I can implement that, but it doesn't have to be named after the Game
ID, it has to be named after the name of the game. For example, "Super
Mario Galaxy" not "RMGE01"

**Comment by LeonardFiedrowicz** [comment]
Oh, I guess I misread that. After ripping the games they were automatically named after the game ID so I assumed it was that way. Thank you for trying to implement it ^^

**Comment by LeonardFiedrowicz** [comment]
The plugin actually already uses os.walk which works with subfolders. The plugin didnt work for me though because I changed the folder name. You can replace that with
        filename = os.path.expandvars(os.path.dirname(os.path.abspath(__file__)) + '\Index.txt')
in line 39 of the backend.py

**Comment by JTNDev** [comment]
Thanks for the help!

**Comment by LeonardFiedrowicz** [comment]
Small correction I mean line 41 with this
        file = ElementTree.parse(os.path.expandvars(os.path.dirname(os.path.abspath(\_\_file\_\_)) + '\games.xml'))

**Comment by LeonardFiedrowicz** [comment]
Also, any idea how to get it working when not all games get recognized?

**Comment by LeonardFiedrowicz** [comment]
Also, you can read the title id from the game file directly (at least I tried it with .wbfs files) so you wouldn't need to rename the files. I don't know how well that works with other file formats though.

**Comment by JTNDev** [comment]
Sorry for the late response. I'm adding support for any folder name right now, and how were you able to get it to read the title ID?

**Comment by LeonardFiedrowicz** [comment]
`with open(file_path, "rb") as f:
    f.seek(0x200)
    print(f.read(6))`

That reads 6 bytes at adress 0x200 of the game file where for .wbfs files the title id is.
I just noticed that that may only work for .wbfs files. It doesn't work for .gcz files for example.

**Comment by LeonardFiedrowicz** [comment]
A bit off-topic, I'm having a bit of troubling with updating game playtimes while GOG is running with my Cemu plugin.
I want to have an infinite loop that checks every minute if the game time in some file is changed but it only does that until the calling function quits so about twice. Do you have an idea how to make it run until gog closes?

**Comment by JTNDev** [comment]
No, I'm actually having the exact same issue

**Comment by LeonardFiedrowicz** [comment]
Please tell me if/when you do find a solution.
